<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?><?= esc($title) ?><?= $this->endSection() ?>

<?= $this->section('content') ?>
<?php
$field = $side === 'sales' ? 'customer_id' : 'supplier_id';
$baseRoute = $side . '/master';
$statusButton = static fn (string $status): string => $status === 'active' ? 'Hapus' : 'Aktifkan';
$nextStatus = static fn (string $status): string => $status === 'active' ? 'inactive' : 'active';
?>
<div class="page-title-box d-flex align-items-center justify-content-between">
    <div>
        <h4 class="mb-sm-0 font-size-18"><?= esc($title) ?></h4>
        <p class="text-muted mb-0"><?= esc($tenantContext['company_name']) ?> / <?= esc($partnerLabel) ?> dan reference master</p>
    </div>
    <?php if ($canManage) : ?>
        <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">Tambah Data</button>
            <div class="dropdown-menu dropdown-menu-end">
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addPartner"><?= esc($partnerLabel) ?></button>
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addTerm">Terms</button>
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addProfile">Profile & Policy</button>
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addAddress">Address Mapping</button>
                <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addPromotion">Promotion</button>
            </div>
        </div>
    <?php else : ?><span class="badge bg-info">Read only</span><?php endif; ?>
</div>
<?php if (session('message') !== null) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors') !== null) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>

<div class="card"><div class="card-body">
    <ul class="nav nav-tabs nav-tabs-custom mb-3">
        <li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#partners"><?= esc($partnerLabel) ?></button></li>
        <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#terms">Terms</button></li>
        <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#profiles">Profile</button></li>
        <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#addresses">Address Mapping</button></li>
        <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#promotions">Promotion</button></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="partners">
            <div class="table-responsive"><table class="table table-hover align-middle mb-0">
                <thead><tr><th>Code / Name</th><th>Currency</th><th>Terms</th><?php if ($side === 'sales') : ?><th>Credit Limit</th><?php endif; ?><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
                <tbody><?php foreach ($partners as $partner) : ?><tr>
                    <td><strong><?= esc($partner['code']) ?></strong><br><small><?= esc($partner['name']) ?></small></td><td><?= esc($partner['currency_code']) ?></td><td><?= esc($partner['term_code'] ?? '-') ?></td><?php if ($side === 'sales') : ?><td><?= number_format((float) $partner['credit_limit'], 2, ',', '.') ?></td><?php endif; ?><td><?= esc($partner['status']) ?></td>
                    <?php if ($canManage) : ?><td class="text-end text-nowrap">
                        <button class="btn btn-outline-primary btn-sm js-edit-partner" data-bs-toggle="modal" data-bs-target="#editPartner" data-id="<?= (int) $partner['id'] ?>" data-code="<?= esc($partner['code'], 'attr') ?>" data-name="<?= esc($partner['name'], 'attr') ?>" data-tax="<?= esc($partner['tax_no'] ?? '', 'attr') ?>" data-email="<?= esc($partner['email'] ?? '', 'attr') ?>" data-phone="<?= esc($partner['phone'] ?? '', 'attr') ?>" data-currency="<?= (int) $partner['currency_id'] ?>" data-term="<?= (int) ($partner['default_term_id'] ?? 0) ?>" data-limit="<?= esc($partner['credit_limit'] ?? '0', 'attr') ?>">Edit</button>
                        <form class="d-inline" method="post" action="<?= site_url($baseRoute . '/status/partner/' . $partner['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($partner['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $statusButton($partner['status']) ?></button></form>
                    </td><?php endif; ?>
                </tr><?php endforeach; ?><?php if ($partners === []) : ?><tr><td colspan="7" class="text-muted text-center">Belum ada data.</td></tr><?php endif; ?></tbody>
            </table></div>
        </div>
        <div class="tab-pane fade" id="terms"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Code</th><th>Name</th><th>Due Days</th><th>Discount</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody>
            <?php foreach ($terms as $term) : ?><tr><td><strong><?= esc($term['code']) ?></strong></td><td><?= esc($term['name']) ?></td><td><?= esc($term['due_days']) ?></td><td><?= esc($term['discount_days'] . ' / ' . $term['discount_rate']) ?></td><td><?= esc($term['status']) ?></td><?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-term" data-bs-toggle="modal" data-bs-target="#editTerm" data-id="<?= (int) $term['id'] ?>" data-code="<?= esc($term['code'], 'attr') ?>" data-name="<?= esc($term['name'], 'attr') ?>" data-due="<?= (int) $term['due_days'] ?>" data-discount-days="<?= (int) $term['discount_days'] ?>" data-rate="<?= esc($term['discount_rate'], 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url($baseRoute . '/status/term/' . $term['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($term['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $statusButton($term['status']) ?></button></form></td><?php endif; ?></tr><?php endforeach; ?>
            <?php if ($terms === []) : ?><tr><td colspan="6" class="text-muted text-center">Belum ada terms.</td></tr><?php endif; ?></tbody>
        </table></div></div>
        <div class="tab-pane fade" id="profiles"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Partner</th><th>Reference / Contact</th><th>VAT / Warehouse</th><th>PIC</th><th>Limits</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody>
            <?php foreach ($profiles as $profile) : ?><tr><td><?= esc($profile['partner_code'] . ' - ' . $profile['partner_name']) ?></td><td><?= esc($profile['reference_name'] ?? '-') ?><br><small><?= esc($profile['contact_name'] ?? '-') ?></small></td><td><?= esc($profile['tax_code'] ?? '-') ?> / <?= esc($profile['warehouse_code'] ?? '-') ?></td><td><?= esc(($side === 'sales' ? $profile['account_manager_name'] : $profile['buyer_name']) ?? '-') ?></td><td><?= $side === 'purchasing' ? esc($profile['amount_limit'] ?? '-') . ' / ' : '' ?><?= esc($profile['quantity_limit'] ?? '-') ?> qty</td><td><?= esc($profile['status']) ?></td><?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-profile" data-bs-toggle="modal" data-bs-target="#addProfile" data-partner="<?= (int) $profile[$field] ?>" data-reference="<?= esc($profile['reference_name'] ?? '', 'attr') ?>" data-contact="<?= esc($profile['contact_name'] ?? '', 'attr') ?>" data-tax="<?= (int) ($profile['default_tax_code_id'] ?? 0) ?>" data-warehouse="<?= (int) ($profile['default_warehouse_id'] ?? 0) ?>" data-pic="<?= esc(($side === 'sales' ? $profile['account_manager_name'] : $profile['buyer_name']) ?? '', 'attr') ?>" data-amount="<?= esc($profile['amount_limit'] ?? '', 'attr') ?>" data-quantity="<?= esc($profile['quantity_limit'] ?? '', 'attr') ?>" data-days="<?= esc($profile['limit_days'] ?? '', 'attr') ?>" data-description="<?= esc($profile['description'] ?? '', 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url($baseRoute . '/status/profile/' . $profile['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($profile['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $statusButton($profile['status']) ?></button></form></td><?php endif; ?></tr><?php endforeach; ?>
            <?php if ($profiles === []) : ?><tr><td colspan="7" class="text-muted text-center">Belum ada profile.</td></tr><?php endif; ?></tbody>
        </table></div></div>
        <div class="tab-pane fade" id="addresses"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Partner</th><th>Address Master</th><th>Type</th><th>Default</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody>
            <?php foreach ($partnerAddresses as $mapping) : ?><tr><td><?= esc($mapping['partner_code']) ?></td><td><?= esc($mapping['address_code'] . ' - ' . $mapping['address_label']) ?></td><td><?= esc($mapping['address_type']) ?></td><td><?= $mapping['is_default'] ? 'Yes' : 'No' ?></td><?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-address" data-bs-toggle="modal" data-bs-target="#editAddress" data-id="<?= (int) $mapping['id'] ?>" data-partner="<?= (int) $mapping[$field] ?>" data-address="<?= (int) $mapping['address_id'] ?>" data-type="<?= esc($mapping['address_type'], 'attr') ?>" data-default="<?= $mapping['is_default'] ? '1' : '0' ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url($baseRoute . '/status/address/' . $mapping['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($mapping['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $statusButton($mapping['status']) ?></button></form></td><?php endif; ?></tr><?php endforeach; ?>
            <?php if ($partnerAddresses === []) : ?><tr><td colspan="5" class="text-muted text-center">Belum ada address mapping.</td></tr><?php endif; ?></tbody></table></div></div>
        <div class="tab-pane fade" id="promotions"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Code / Name</th><th>Partner</th><th>Discount</th><th>Periode</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody>
            <?php foreach ($promotions as $promo) : ?><tr><td><strong><?= esc($promo['code']) ?></strong><br><small><?= esc($promo['name']) ?></small></td><td><?= esc($promo['partner_code'] ?? 'All') ?></td><td><?= esc($promo['discount_type'] . ' / ' . $promo['discount_value']) ?></td><td><?= esc($promo['starts_on'] . ' s.d. ' . $promo['ends_on']) ?></td><td><?= esc($promo['status']) ?></td><?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-promotion" data-bs-toggle="modal" data-bs-target="#editPromotion" data-id="<?= (int) $promo['id'] ?>" data-code="<?= esc($promo['code'], 'attr') ?>" data-name="<?= esc($promo['name'], 'attr') ?>" data-partner="<?= (int) ($promo[$field] ?? 0) ?>" data-type="<?= esc($promo['discount_type'], 'attr') ?>" data-value="<?= esc($promo['discount_value'], 'attr') ?>" data-start="<?= esc($promo['starts_on'], 'attr') ?>" data-end="<?= esc($promo['ends_on'], 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url($baseRoute . '/status/promotion/' . $promo['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($promo['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $statusButton($promo['status']) ?></button></form></td><?php endif; ?></tr><?php endforeach; ?>
            <?php if ($promotions === []) : ?><tr><td colspan="6" class="text-muted text-center">Belum ada promo.</td></tr><?php endif; ?></tbody></table></div></div>
    </div>
</div></div>

<?php if ($canManage) : ?>
<div class="modal fade" id="addTerm"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url($baseRoute . '/terms') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Terms</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-4"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="col-8"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-4"><label class="form-label">Due Days</label><input type="number" min="0" name="due_days" value="30" class="form-control" required></div><div class="col-4"><label class="form-label">Disc Days</label><input type="number" min="0" name="discount_days" value="0" class="form-control" required></div><div class="col-4"><label class="form-label">Disc Rate</label><input type="number" step="0.000001" min="0" name="discount_rate" value="0" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editTerm"><div class="modal-dialog"><form class="modal-content" method="post" data-action="<?= site_url($baseRoute . '/terms') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Terms</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-4"><label class="form-label">Code</label><input data-field="code" class="form-control" readonly></div><div class="col-8"><label class="form-label">Name</label><input name="name" data-field="name" class="form-control" required></div><div class="col-4"><label class="form-label">Due Days</label><input type="number" min="0" name="due_days" data-field="due" class="form-control" required></div><div class="col-4"><label class="form-label">Disc Days</label><input type="number" min="0" name="discount_days" data-field="discount-days" class="form-control" required></div><div class="col-4"><label class="form-label">Disc Rate</label><input type="number" step="0.000001" min="0" name="discount_rate" data-field="rate" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal fade" id="addPartner"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url($baseRoute . '/partners') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah <?= esc($partnerLabel) ?></h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-3"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="col-md-5"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-4"><label class="form-label">NPWP</label><input name="tax_no" class="form-control"></div><div class="col-md-4"><label class="form-label">Email</label><input name="email" type="email" class="form-control"></div><div class="col-md-3"><label class="form-label">Phone</label><input name="phone" class="form-control"></div><div class="col-md-2"><label class="form-label">Currency</label><select name="currency_id" class="form-select"><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Terms</label><select name="default_term_id" class="form-select"><option value="">-</option><?php foreach ($terms as $term) : ?><option value="<?= (int) $term['id'] ?>"><?= esc($term['code']) ?></option><?php endforeach; ?></select></div><?php if ($side === 'sales') : ?><div class="col-md-3"><label class="form-label">Credit Limit</label><input type="number" min="0" step="0.0001" name="credit_limit" value="0" class="form-control"></div><?php endif; ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editPartner"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" data-action="<?= site_url($baseRoute . '/partners') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit <?= esc($partnerLabel) ?></h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-3"><label class="form-label">Code</label><input data-field="code" class="form-control" readonly></div><div class="col-md-5"><label class="form-label">Name</label><input name="name" data-field="name" class="form-control" required></div><div class="col-md-4"><label class="form-label">NPWP</label><input name="tax_no" data-field="tax" class="form-control"></div><div class="col-md-4"><label class="form-label">Email</label><input name="email" data-field="email" type="email" class="form-control"></div><div class="col-md-3"><label class="form-label">Phone</label><input name="phone" data-field="phone" class="form-control"></div><div class="col-md-2"><label class="form-label">Currency</label><select name="currency_id" data-field="currency" class="form-select"><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Terms</label><select name="default_term_id" data-field="term" class="form-select"><option value="">-</option><?php foreach ($terms as $term) : ?><option value="<?= (int) $term['id'] ?>"><?= esc($term['code']) ?></option><?php endforeach; ?></select></div><?php if ($side === 'sales') : ?><div class="col-md-3"><label class="form-label">Credit Limit</label><input type="number" min="0" step="0.0001" name="credit_limit" data-field="limit" class="form-control"></div><?php endif; ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal fade" id="addProfile"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url($baseRoute . '/profiles') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah / Edit Profile</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-4"><label class="form-label"><?= esc($partnerLabel) ?></label><select name="<?= $field ?>" data-field="partner" class="form-select"><?php foreach ($partners as $partner) : ?><option value="<?= (int) $partner['id'] ?>"><?= esc($partner['code'] . ' - ' . $partner['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Reference</label><input name="reference_name" data-field="reference" class="form-control"></div><div class="col-md-4"><label class="form-label">Contact</label><input name="contact_name" data-field="contact" class="form-control"></div><div class="col-md-3"><label class="form-label">VAT</label><select name="default_tax_code_id" data-field="tax" class="form-select"><option value="">-</option><?php foreach ($taxCodes as $tax) : ?><option value="<?= (int) $tax['id'] ?>"><?= esc($tax['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Warehouse</label><select name="default_warehouse_id" data-field="warehouse" class="form-select"><option value="">-</option><?php foreach ($warehouses as $warehouse) : ?><option value="<?= (int) $warehouse['id'] ?>"><?= esc($warehouse['branch_code'] . '/' . $warehouse['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">PIC</label><input name="<?= $side === 'sales' ? 'account_manager_name' : 'buyer_name' ?>" data-field="pic" class="form-control"></div><?php if ($side === 'purchasing') : ?><div class="col-md-3"><label class="form-label">Amount Limit</label><input name="amount_limit" data-field="amount" type="number" step="0.0001" class="form-control"></div><?php endif; ?><div class="col-md-3"><label class="form-label">Qty Limit</label><input name="quantity_limit" data-field="quantity" type="number" step="0.0001" class="form-control"></div><div class="col-md-3"><label class="form-label">Limit Days</label><input name="limit_days" data-field="days" type="number" class="form-control"></div><div class="col-md-6"><label class="form-label">Description</label><input name="description" data-field="description" class="form-control"></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="addAddress"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url($baseRoute . '/addresses') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Address Mapping</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-12"><label class="form-label">Partner</label><select name="<?= $field ?>" class="form-select"><?php foreach ($partners as $partner) : ?><option value="<?= (int) $partner['id'] ?>"><?= esc($partner['code']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Address</label><select name="address_id" class="form-select"><?php foreach ($addresses as $address) : ?><option value="<?= (int) $address['id'] ?>"><?= esc($address['code']) ?></option><?php endforeach; ?></select></div><div class="col-8"><label class="form-label">Type</label><select name="address_type" class="form-select"><option value="billing">Billing</option><option value="shipping">Shipping</option><option value="mailing">Mailing</option><option value="office">Office</option><option value="pickup">Pickup</option></select></div><div class="col-4 form-check mt-4"><input type="checkbox" name="is_default" value="1" class="form-check-input"><label class="form-check-label">Default</label></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editAddress"><div class="modal-dialog"><form class="modal-content" method="post" data-action="<?= site_url($baseRoute . '/addresses') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Address Mapping</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-12"><label class="form-label">Partner</label><select name="<?= $field ?>" data-field="partner" class="form-select"><?php foreach ($partners as $partner) : ?><option value="<?= (int) $partner['id'] ?>"><?= esc($partner['code']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Address</label><select name="address_id" data-field="address" class="form-select"><?php foreach ($addresses as $address) : ?><option value="<?= (int) $address['id'] ?>"><?= esc($address['code']) ?></option><?php endforeach; ?></select></div><div class="col-8"><label class="form-label">Type</label><select name="address_type" data-field="type" class="form-select"><option value="billing">Billing</option><option value="shipping">Shipping</option><option value="mailing">Mailing</option><option value="office">Office</option><option value="pickup">Pickup</option></select></div><div class="col-4 form-check mt-4"><input type="checkbox" name="is_default" value="1" data-field="default" class="form-check-input"><label class="form-check-label">Default</label></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal fade" id="addPromotion"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url($baseRoute . '/promotions') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Promotion</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-3"><label class="form-label">Partner</label><select name="<?= $field ?>" class="form-select"><option value="">All</option><?php foreach ($partners as $partner) : ?><option value="<?= (int) $partner['id'] ?>"><?= esc($partner['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="col-md-6"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-3"><label class="form-label">Type</label><select name="discount_type" class="form-select"><option value="percentage">Percentage</option><option value="amount">Amount</option></select></div><div class="col-md-3"><label class="form-label">Value</label><input name="discount_value" type="number" step="0.0001" min="0.0001" class="form-control"></div><div class="col-md-3"><label class="form-label">Start</label><input name="starts_on" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">End</label><input name="ends_on" type="date" class="form-control"></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editPromotion"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" data-action="<?= site_url($baseRoute . '/promotions') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Promotion</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-3"><label class="form-label">Partner</label><select name="<?= $field ?>" data-field="partner" class="form-select"><option value="">All</option><?php foreach ($partners as $partner) : ?><option value="<?= (int) $partner['id'] ?>"><?= esc($partner['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Code</label><input data-field="code" class="form-control" readonly></div><div class="col-md-6"><label class="form-label">Name</label><input name="name" data-field="name" class="form-control" required></div><div class="col-md-3"><label class="form-label">Type</label><select name="discount_type" data-field="type" class="form-select"><option value="percentage">Percentage</option><option value="amount">Amount</option></select></div><div class="col-md-3"><label class="form-label">Value</label><input name="discount_value" data-field="value" type="number" step="0.0001" min="0.0001" class="form-control"></div><div class="col-md-3"><label class="form-label">Start</label><input name="starts_on" data-field="start" type="date" class="form-control"></div><div class="col-md-3"><label class="form-label">End</label><input name="ends_on" data-field="end" type="date" class="form-control"></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<?php endif; ?>
<?= $this->endSection() ?>

<?php if ($canManage) : ?>
<?= $this->section('scripts') ?>
<script>
document.querySelectorAll('.js-edit-term').forEach(function (button) { button.addEventListener('click', function () { var f = document.querySelector('#editTerm form'); f.action = f.dataset.action + '/' + button.dataset.id; f.querySelector('[data-field="code"]').value = button.dataset.code; f.querySelector('[data-field="name"]').value = button.dataset.name; f.querySelector('[data-field="due"]').value = button.dataset.due; f.querySelector('[data-field="discount-days"]').value = button.dataset.discountDays; f.querySelector('[data-field="rate"]').value = button.dataset.rate; }); });
document.querySelectorAll('.js-edit-partner').forEach(function (button) { button.addEventListener('click', function () { var f = document.querySelector('#editPartner form'); f.action = f.dataset.action + '/' + button.dataset.id; ['code','name','tax','email','phone','currency','term','limit'].forEach(function (key) { var e = f.querySelector('[data-field="' + key + '"]'); if (e) { e.value = button.dataset[key] === '0' ? '' : button.dataset[key]; } }); }); });
document.querySelectorAll('.js-edit-profile').forEach(function (button) { button.addEventListener('click', function () { var f = document.querySelector('#addProfile form'); ['partner','reference','contact','tax','warehouse','pic','amount','quantity','days','description'].forEach(function (key) { var e = f.querySelector('[data-field="' + key + '"]'); if (e) { e.value = button.dataset[key] === '0' ? '' : button.dataset[key]; } }); }); });
document.querySelectorAll('.js-edit-address').forEach(function (button) { button.addEventListener('click', function () { var f = document.querySelector('#editAddress form'); f.action = f.dataset.action + '/' + button.dataset.id; ['partner','address','type'].forEach(function (key) { f.querySelector('[data-field="' + key + '"]').value = button.dataset[key]; }); f.querySelector('[data-field="default"]').checked = button.dataset.default === '1'; }); });
document.querySelectorAll('.js-edit-promotion').forEach(function (button) { button.addEventListener('click', function () { var f = document.querySelector('#editPromotion form'); f.action = f.dataset.action + '/' + button.dataset.id; ['code','name','partner','type','value','start','end'].forEach(function (key) { var e = f.querySelector('[data-field="' + key + '"]'); e.value = button.dataset[key] === '0' ? '' : button.dataset[key]; }); }); });
</script>
<?= $this->endSection() ?>
<?php endif; ?>
