<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>Transaction Code<?= $this->endSection() ?>

<?= $this->section('content') ?>
<div class="page-title-box"><h4 class="mb-sm-0 font-size-18">Transaction Code</h4><p class="text-muted mb-0">Pengganti Prefix & Numbering</p></div>
<?php if (session('message')) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors')) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="row"><div class="col-xl-4"><div class="card"><div class="card-body"><h4 class="card-title">Create Transaction Code</h4><?php if ($canManage) : ?><form method="post" action="<?= site_url('setup/transaction-codes') ?>"><?= csrf_field() ?><div class="mb-2"><label class="form-label">Site</label><select name="branch_id" class="form-select"><option value="">Company Scope</option><?php foreach ($branches as $branch) : ?><option value="<?= (int) $branch['id'] ?>"><?= esc($branch['code'] . ' - ' . $branch['name']) ?></option><?php endforeach; ?></select></div><div class="mb-2"><label class="form-label">Module</label><input name="module" class="form-control" required></div><div class="mb-2"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="mb-2"><label class="form-label">Prefix</label><input name="prefix" class="form-control" required></div><div class="row g-2"><div class="col-md-6"><label class="form-label">Length</label><input type="number" name="number_length" value="5" class="form-control" required></div><div class="col-md-6"><label class="form-label">Reset</label><select name="reset_rule" class="form-select"><option value="never">Never</option><option value="yearly">Yearly</option><option value="monthly">Monthly</option><option value="daily">Daily</option></select></div></div><button class="btn btn-primary mt-3">Simpan</button></form><?php else : ?><div class="alert alert-info">Read only.</div><?php endif; ?></div></div></div><div class="col-xl-8"><div class="card"><div class="card-body"><h4 class="card-title">Transaction Code List</h4><div class="table-responsive"><table class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Module</th><th>Code</th><th>Prefix</th><th>Next</th><th>Length</th><th>Reset</th><th>Site</th><th>Status</th></tr></thead><tbody><?php foreach ($transaction_codes as $row) : ?><tr><td><?= esc($row['module']) ?></td><td><?= esc($row['code']) ?></td><td><?= esc($row['prefix']) ?></td><td><?= esc($row['next_number']) ?></td><td><?= esc($row['number_length']) ?></td><td><?= esc($row['reset_rule']) ?></td><td><?= esc($row['branch_code'] ?? '-') ?></td><td><?= esc($row['status']) ?></td></tr><?php endforeach; ?><?php if ($transaction_codes === []) : ?><tr><td colspan="8" class="text-center text-muted">Belum ada transaction code.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
<?= $this->endSection() ?>
