<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>VAT<?= $this->endSection() ?>

<?= $this->section('content') ?>
<div class="page-title-box"><h4 class="mb-sm-0 font-size-18">VAT</h4><p class="text-muted mb-0">Tax/VAT code master</p></div>
<?php if (session('message')) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors')) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="row"><div class="col-xl-4"><div class="card"><div class="card-body"><h4 class="card-title">Create VAT</h4><?php if ($canManage) : ?><form method="post" action="<?= site_url('setup/tax-codes') ?>"><?= csrf_field() ?><div class="mb-2"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="mb-2"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="mb-2"><label class="form-label">Type</label><select name="tax_type" class="form-select"><option value="input">Input</option><option value="output">Output</option><option value="both">Both</option></select></div><div class="mb-2"><label class="form-label">Rate</label><input type="number" step="0.000001" name="rate" class="form-control" required></div><button class="btn btn-primary mt-2">Simpan</button></form><?php else : ?><div class="alert alert-info">Read only.</div><?php endif; ?></div></div></div><div class="col-xl-8"><div class="card"><div class="card-body"><h4 class="card-title">VAT List</h4><div class="table-responsive"><table class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Code</th><th>Name</th><th>Type</th><th>Rate</th><th>Status</th></tr></thead><tbody><?php foreach ($tax_codes as $row) : ?><tr><td><?= esc($row['code']) ?></td><td><?= esc($row['name']) ?></td><td><?= esc($row['tax_type']) ?></td><td><?= esc($row['rate']) ?></td><td><?= esc($row['status']) ?></td></tr><?php endforeach; ?><?php if ($tax_codes === []) : ?><tr><td colspan="5" class="text-center text-muted">Belum ada VAT.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
<?= $this->endSection() ?>
