<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>Address Master<?= $this->endSection() ?>

<?= $this->section('content') ?>
<div class="page-title-box"><h4 class="mb-sm-0 font-size-18">Address Master</h4><p class="text-muted mb-0">Reusable address data for customer, supplier, warehouse and company.</p></div>
<?php if (session('message')) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors')) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="row"><div class="col-xl-4"><div class="card"><div class="card-body"><h4 class="card-title">Create Address</h4><?php if ($canManage) : ?><form method="post" action="<?= site_url('setup/addresses') ?>"><?= csrf_field() ?><div class="mb-2"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="mb-2"><label class="form-label">Label</label><input name="label" class="form-control" required></div><div class="mb-2"><label class="form-label">Address</label><textarea name="address_line1" class="form-control" required></textarea></div><div class="mb-2"><label class="form-label">Country</label><select name="country_id" class="form-select" required><?php foreach ($countries as $country) : ?><option value="<?= (int) $country['id'] ?>"><?= esc($country['name']) ?></option><?php endforeach; ?></select></div><div class="mb-2"><label class="form-label">Village ID</label><input name="village_id" class="form-control" placeholder="Optional village id"></div><div class="mb-2"><label class="form-label">Postal Code</label><input name="postal_code" class="form-control" maxlength="10"></div><button class="btn btn-primary mt-2">Simpan</button></form><?php else : ?><div class="alert alert-info">Read only.</div><?php endif; ?></div></div></div><div class="col-xl-8"><div class="card"><div class="card-body"><h4 class="card-title">Address List</h4><div class="table-responsive"><table class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Code</th><th>Label</th><th>Address</th><th>Country</th><th>City</th><th>Postal</th><th>Status</th></tr></thead><tbody><?php foreach ($addresses as $row) : ?><tr><td><?= esc($row['code']) ?></td><td><?= esc($row['label']) ?></td><td><?= esc($row['address_line1']) ?></td><td><?= esc($row['country_name']) ?></td><td><?= esc($row['city_name'] ?? '-') ?></td><td><?= esc($row['postal_code'] ?? '-') ?></td><td><?= esc($row['status']) ?></td></tr><?php endforeach; ?><?php if ($addresses === []) : ?><tr><td colspan="7" class="text-center text-muted">Belum ada address.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
<?= $this->endSection() ?>
