<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>Department<?= $this->endSection() ?>

<?= $this->section('content') ?>
<div class="page-title-box"><h4 class="mb-sm-0 font-size-18">Department</h4><p class="text-muted mb-0">Department per site/company</p></div>
<?php if (session('message')) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors')) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>
<div class="row"><div class="col-xl-4"><div class="card"><div class="card-body"><h4 class="card-title">Create Department</h4><?php if ($canManage) : ?><form method="post" action="<?= site_url('setup/departments') ?>"><?= csrf_field() ?><div class="mb-2"><label class="form-label">Site</label><select name="branch_id" class="form-select" required><?php foreach ($branches as $branch) : ?><option value="<?= (int) $branch['id'] ?>"><?= esc($branch['code'] . ' - ' . $branch['name']) ?></option><?php endforeach; ?></select></div><div class="mb-2"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="mb-2"><label class="form-label">Name</label><input name="name" class="form-control" required></div><button class="btn btn-primary mt-2">Simpan</button></form><?php else : ?><div class="alert alert-info">Read only.</div><?php endif; ?></div></div></div><div class="col-xl-8"><div class="card"><div class="card-body"><h4 class="card-title">Department List</h4><div class="table-responsive"><table class="table table-sm table-bordered align-middle"><thead class="table-light"><tr><th>Site</th><th>Code</th><th>Name</th><th>Status</th></tr></thead><tbody><?php foreach ($departments as $row) : ?><tr><td><?= esc($row['branch_code'] ?? '-') ?></td><td><?= esc($row['code']) ?></td><td><?= esc($row['name']) ?></td><td><?= esc($row['status']) ?></td></tr><?php endforeach; ?><?php if ($departments === []) : ?><tr><td colspan="4" class="text-center text-muted">Belum ada department.</td></tr><?php endif; ?></tbody></table></div></div></div></div></div>
<?= $this->endSection() ?>
