<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>Finance Master<?= $this->endSection() ?>

<?= $this->section('content') ?>
<?php $nextStatus = static fn (string $status): string => $status === 'active' ? 'inactive' : 'active'; ?>
<div class="page-title-box d-flex align-items-center justify-content-between">
    <div>
        <h4 class="mb-sm-0 font-size-18">Finance Master</h4>
        <p class="text-muted mb-0"><?= esc($tenantContext['company_name']) ?> / COA, kas-bank, dan kurs</p>
    </div>
    <?php if ($canManage) : ?>
        <div class="dropdown"><button class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">Tambah Data</button><div class="dropdown-menu">
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addAccount">Chart of Account</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addCashBank">Cash/Bank Account</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addRate">Exchange Rate</button>
            <div class="dropdown-divider"></div>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addGlBook">GL Book</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addGlColumn">GL Column</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addCostType">Cost Type</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addItemCost">Item Cost</button>
            <div class="dropdown-divider"></div>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addFiscalPeriod">Fiscal Period</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#closeModulePeriod">Close Module Period</button>
            <div class="dropdown-divider"></div>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addJournal">Manual Journal</button>
            <a class="dropdown-item" href="<?= site_url('finance/invoices') ?>">Invoice / Payment</a>
        </div></div>
    <?php else : ?><span class="badge bg-info">Read only</span><?php endif; ?>
</div>
<?php if (session('message') !== null) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors') !== null) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>

<ul class="nav nav-tabs mb-3" role="tablist">
    <li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#coa">Chart of Accounts</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#cash-bank">Cash &amp; Bank</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#rates">Exchange Rate</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#gl-setup">GL Setup</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#costing">Costing</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#period-close">Period Close</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#journals">GL Entry</button></li>
</ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="coa"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>Code</th><th>Account Name</th><th>Type</th><th>Parent</th><th>Normal</th><th>Posting</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($accounts as $account) : ?><tr>
        <td><strong><?= esc($account['account_code']) ?></strong></td><td><?= esc($account['account_name']) ?></td><td><?= esc($account['account_type']) ?></td><td><?= esc($account['parent_code'] ?? '-') ?></td><td><?= esc($account['normal_balance']) ?></td><td><?= (bool) $account['is_postable'] ? 'Ya' : 'Tidak' ?></td><td><?= esc($account['status']) ?></td>
        <?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-account" data-bs-toggle="modal" data-bs-target="#editAccount" data-id="<?= (int) $account['id'] ?>" data-name="<?= esc($account['account_name'], 'attr') ?>" data-parent="<?= (int) ($account['parent_id'] ?? 0) ?>" data-type="<?= esc($account['account_type'], 'attr') ?>" data-normal="<?= esc($account['normal_balance'], 'attr') ?>" data-postable="<?= (int) $account['is_postable'] ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url('finance/master/status/account/' . $account['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($account['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $account['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?>
    </tr><?php endforeach; ?><?php if ($accounts === []) : ?><tr><td colspan="<?= $canManage ? '8' : '7' ?>" class="text-center text-muted py-4">Belum ada akun.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
<div class="tab-pane fade" id="cash-bank"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>Code / Name</th><th>Type</th><th>Site</th><th>COA</th><th>Currency</th><th>Bank / Rekening</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($cashBanks as $cashBank) : ?><tr>
        <td><strong><?= esc($cashBank['code']) ?></strong><br><small><?= esc($cashBank['name']) ?></small></td><td><?= esc($cashBank['account_type']) ?></td><td><?= esc($cashBank['branch_code'] ?? 'All') ?></td><td><?= esc($cashBank['account_code']) ?></td><td><?= esc($cashBank['currency_code']) ?></td><td><?= esc(trim(($cashBank['bank_name'] ?? '') . ' ' . ($cashBank['account_number_masked'] ?? '')) ?: '-') ?></td><td><?= esc($cashBank['status']) ?></td>
        <?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-bank" data-bs-toggle="modal" data-bs-target="#editCashBank" data-id="<?= (int) $cashBank['id'] ?>" data-name="<?= esc($cashBank['name'], 'attr') ?>" data-type="<?= esc($cashBank['account_type'], 'attr') ?>" data-branch="<?= (int) ($cashBank['branch_id'] ?? 0) ?>" data-account="<?= (int) $cashBank['account_id'] ?>" data-currency="<?= (int) $cashBank['currency_id'] ?>" data-bank="<?= esc($cashBank['bank_name'] ?? '', 'attr') ?>" data-number="<?= esc($cashBank['account_number_masked'] ?? '', 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url('finance/master/status/cash-bank/' . $cashBank['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($cashBank['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $cashBank['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?>
    </tr><?php endforeach; ?><?php if ($cashBanks === []) : ?><tr><td colspan="<?= $canManage ? '8' : '7' ?>" class="text-center text-muted py-4">Belum ada kas/bank.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
<div class="tab-pane fade" id="rates"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>Date</th><th>Currency</th><th>Type</th><th>Rate to Base</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($rates as $rate) : ?><tr>
        <td><?= esc($rate['rate_date']) ?></td><td><?= esc($rate['currency_code']) ?></td><td><?= esc($rate['rate_type']) ?></td><td><?= esc($rate['rate_to_base']) ?></td><td><?= esc($rate['status']) ?></td>
        <?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-rate" data-bs-toggle="modal" data-bs-target="#editRate" data-id="<?= (int) $rate['id'] ?>" data-currency="<?= (int) $rate['currency_id'] ?>" data-date="<?= esc($rate['rate_date'], 'attr') ?>" data-type="<?= esc($rate['rate_type'], 'attr') ?>" data-rate="<?= esc($rate['rate_to_base'], 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url('finance/master/status/exchange-rate/' . $rate['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($rate['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $rate['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?>
    </tr><?php endforeach; ?><?php if ($rates === []) : ?><tr><td colspan="<?= $canManage ? '6' : '5' ?>" class="text-center text-muted py-4">Belum ada kurs.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
<div class="tab-pane fade" id="gl-setup">
    <div class="row">
        <div class="col-xl-7"><div class="card"><div class="card-body"><h4 class="card-title mb-3">GL Book</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Code / Name</th><th>Type</th><th>Currency</th><th>Retained Earnings</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
            <tbody><?php foreach ($glBooks as $book) : ?><tr><td><strong><?= esc($book['code']) ?></strong><br><small><?= esc($book['name']) ?></small></td><td><?= esc($book['book_type']) ?></td><td><?= esc($book['currency_code']) ?></td><td><?= esc($book['retained_earnings_code'] ?? '-') ?></td><td><?= esc($book['status']) ?></td><?php if ($canManage) : ?><td class="text-end"><form method="post" action="<?= site_url('finance/master/status/gl-book/' . $book['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($book['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $book['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?></tr><?php endforeach; ?><?php if ($glBooks === []) : ?><tr><td colspan="<?= $canManage ? '6' : '5' ?>" class="text-center text-muted py-4">Belum ada GL Book.</td></tr><?php endif; ?></tbody>
        </table></div></div></div></div>
        <div class="col-xl-5"><div class="card"><div class="card-body"><h4 class="card-title mb-3">GL Column</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Seq</th><th>Code / Name</th><th>Type</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
            <tbody><?php foreach ($glColumns as $column) : ?><tr><td><?= esc($column['sequence_no']) ?></td><td><strong><?= esc($column['code']) ?></strong><br><small><?= esc($column['name']) ?></small></td><td><?= esc($column['column_type']) ?></td><td><?= esc($column['status']) ?></td><?php if ($canManage) : ?><td class="text-end"><form method="post" action="<?= site_url('finance/master/status/gl-column/' . $column['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($column['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $column['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?></tr><?php endforeach; ?><?php if ($glColumns === []) : ?><tr><td colspan="<?= $canManage ? '5' : '4' ?>" class="text-center text-muted py-4">Belum ada GL Column.</td></tr><?php endif; ?></tbody>
        </table></div></div></div></div>
    </div>
</div>
<div class="tab-pane fade" id="costing">
    <div class="row">
        <div class="col-xl-4"><div class="card"><div class="card-body"><h4 class="card-title mb-3">Cost Type</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Code / Name</th><th>Method</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
            <tbody><?php foreach ($costTypes as $type) : ?><tr><td><strong><?= esc($type['code']) ?></strong><br><small><?= esc($type['name']) ?></small></td><td><?= esc($type['valuation_method']) ?></td><td><?= esc($type['status']) ?></td><?php if ($canManage) : ?><td class="text-end"><form method="post" action="<?= site_url('finance/master/status/cost-type/' . $type['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($type['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $type['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?></tr><?php endforeach; ?><?php if ($costTypes === []) : ?><tr><td colspan="<?= $canManage ? '4' : '3' ?>" class="text-center text-muted py-4">Belum ada Cost Type.</td></tr><?php endif; ?></tbody>
        </table></div></div></div></div>
        <div class="col-xl-8"><div class="card"><div class="card-body"><h4 class="card-title mb-3">Item Cost</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Item</th><th>Cost Type</th><th>Cost</th><th>Effective</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
            <tbody><?php foreach ($itemCosts as $cost) : ?><tr><td><strong><?= esc($cost['sku']) ?></strong><br><small><?= esc($cost['product_name']) ?></small></td><td><?= esc($cost['cost_type_code']) ?></td><td><?= esc($cost['currency_code'] . ' ' . number_format((float) $cost['unit_cost'], 2, ',', '.')) ?></td><td><?= esc($cost['effective_from']) ?></td><td><?= esc($cost['status']) ?></td><?php if ($canManage) : ?><td class="text-end"><form method="post" action="<?= site_url('finance/master/status/item-cost/' . $cost['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($cost['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $cost['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?></tr><?php endforeach; ?><?php if ($itemCosts === []) : ?><tr><td colspan="<?= $canManage ? '6' : '5' ?>" class="text-center text-muted py-4">Belum ada Item Cost.</td></tr><?php endif; ?></tbody>
        </table></div></div></div></div>
    </div>
</div>
<div class="tab-pane fade" id="period-close">
    <div class="row">
        <div class="col-xl-6"><div class="card"><div class="card-body"><h4 class="card-title mb-3">Fiscal Periods</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Period</th><th>Date Range</th><th>Status</th><th>Locked At</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
            <tbody><?php foreach ($fiscalPeriods as $period) : ?><tr><td><strong><?= esc($period['year'] . '/' . str_pad((string) $period['period'], 2, '0', STR_PAD_LEFT)) ?></strong></td><td><?= esc($period['starts_on'] . ' - ' . $period['ends_on']) ?></td><td><?= esc($period['status']) ?></td><td><?= esc($period['locked_at'] ?? '-') ?></td><?php if ($canManage) : ?><td class="text-end"><?php if ($period['status'] === 'open') : ?><form method="post" action="<?= site_url('finance/master/fiscal-periods/' . $period['id'] . '/close') ?>"><?= csrf_field() ?><button class="btn btn-outline-danger btn-sm">Lock</button></form><?php else : ?><form method="post" action="<?= site_url('finance/master/fiscal-periods/' . $period['id'] . '/reopen') ?>"><?= csrf_field() ?><button class="btn btn-outline-primary btn-sm">Reopen</button></form><?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if ($fiscalPeriods === []) : ?><tr><td colspan="<?= $canManage ? '5' : '4' ?>" class="text-center text-muted py-4">Belum ada fiscal period.</td></tr><?php endif; ?></tbody>
        </table></div></div></div></div>
        <div class="col-xl-6"><div class="card"><div class="card-body"><h4 class="card-title mb-3">Module Period Close</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
            <thead><tr><th>Period</th><th>Module</th><th>Status</th><th>Closed At</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
            <tbody><?php foreach ($moduleCloses as $close) : ?><tr><td><?= esc($close['year'] . '/' . str_pad((string) $close['period'], 2, '0', STR_PAD_LEFT)) ?></td><td><?= esc($close['module_code']) ?></td><td><?= esc($close['status']) ?></td><td><?= esc($close['closed_at'] ?? '-') ?></td><?php if ($canManage) : ?><td class="text-end"><?php if ($close['status'] === 'closed') : ?><form method="post" action="<?= site_url('finance/master/module-periods/' . $close['id'] . '/reopen') ?>"><?= csrf_field() ?><button class="btn btn-outline-primary btn-sm">Reopen</button></form><?php else : ?>-<?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if ($moduleCloses === []) : ?><tr><td colspan="<?= $canManage ? '5' : '4' ?>" class="text-center text-muted py-4">Belum ada module close.</td></tr><?php endif; ?></tbody>
        </table></div></div></div></div>
    </div>
</div>
<div class="tab-pane fade" id="journals"><div class="card"><div class="card-body"><h4 class="card-title mb-3">GL Entry</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>No / Date</th><th>Book</th><th>Description</th><th>Debit</th><th>Credit</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($journals as $journal) : ?><tr><td><strong><?= esc($journal['journal_no']) ?></strong><br><small><?= esc($journal['journal_date']) ?></small></td><td><?= esc($journal['gl_book_code']) ?></td><td><?= esc($journal['description']) ?></td><td><?= esc(number_format((float) $journal['total_debit'], 2, ',', '.')) ?></td><td><?= esc(number_format((float) $journal['total_credit'], 2, ',', '.')) ?></td><td><?= esc($journal['status']) ?></td><?php if ($canManage) : ?><td class="text-end"><?php if ($journal['status'] === 'draft') : ?><form method="post" action="<?= site_url('finance/master/journals/' . $journal['id'] . '/post') ?>"><?= csrf_field() ?><button class="btn btn-primary btn-sm">Post</button></form><?php else : ?>-<?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if ($journals === []) : ?><tr><td colspan="<?= $canManage ? '7' : '6' ?>" class="text-center text-muted py-4">Belum ada journal entry.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
</div>

<?php if ($canManage) : ?>
<div class="modal fade" id="addAccount"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Chart of Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-4"><label class="form-label">Code</label><input name="account_code" class="form-control" required></div><div class="col-8"><label class="form-label">Account Name</label><input name="account_name" class="form-control" required></div><?php include __DIR__ . '/partials/account_fields.php'; ?>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editAccount"><div class="modal-dialog"><form class="modal-content js-account-form" method="post" data-action="<?= site_url('finance/master/accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Chart of Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-12"><label class="form-label">Account Name</label><input name="account_name" data-field="name" class="form-control" required></div><?php include __DIR__ . '/partials/account_fields.php'; ?>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<?php $bankFields = static function () use ($branches, $postable, $currencies): void { ?>
<div class="col-md-6"><label class="form-label">Name</label><input name="name" data-field="name" class="form-control" required></div><div class="col-md-3"><label class="form-label">Type</label><select name="account_type" data-field="type" class="form-select"><option value="cash">Cash</option><option value="bank">Bank</option></select></div><div class="col-md-3"><label class="form-label">Site</label><select name="branch_id" data-field="branch" class="form-select"><option value="">All</option><?php foreach ($branches as $branch) : ?><option value="<?= (int) $branch['id'] ?>"><?= esc($branch['code']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">COA Posting</label><select name="account_id" data-field="account" class="form-select" required><?php foreach ($postable as $account) : ?><option value="<?= (int) $account['id'] ?>"><?= esc($account['account_code'] . ' - ' . $account['account_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Currency</label><select name="currency_id" data-field="currency" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Bank Name</label><input name="bank_name" data-field="bank" class="form-control"></div><div class="col-md-6"><label class="form-label">Masked Account No.</label><input name="account_number_masked" data-field="number" class="form-control" placeholder="****1234"></div>
<?php }; ?>
<div class="modal fade" id="addCashBank"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/master/cash-bank-accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Cash/Bank Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-3"><label class="form-label">Code</label><input name="code" class="form-control" required></div><?php $bankFields(); ?></div><div class="modal-footer"><button class="btn btn-primary" <?= $postable === [] ? 'disabled' : '' ?>>Simpan</button></div></form></div></div>
<div class="modal fade" id="editCashBank"><div class="modal-dialog modal-lg"><form class="modal-content js-bank-form" method="post" data-action="<?= site_url('finance/master/cash-bank-accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Cash/Bank Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><?php $bankFields(); ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<?php $rateFields = static function () use ($currencies): void { ?><div class="col-md-4"><label class="form-label">Currency</label><select name="currency_id" data-field="currency" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Date</label><input type="date" name="rate_date" data-field="date" class="form-control" required></div><div class="col-md-4"><label class="form-label">Type</label><select name="rate_type" data-field="type" class="form-select"><option value="middle">Middle</option><option value="buy">Buy</option><option value="sell">Sell</option></select></div><div class="col-md-6"><label class="form-label">Rate to Base</label><input name="rate_to_base" data-field="rate" class="form-control" required></div><?php }; ?>
<div class="modal fade" id="addRate"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/exchange-rates') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Exchange Rate</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><?php $rateFields(); ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editRate"><div class="modal-dialog"><form class="modal-content js-rate-form" method="post" data-action="<?= site_url('finance/master/exchange-rates') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Exchange Rate</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><?php $rateFields(); ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<div class="modal fade" id="addGlBook"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/master/gl-books') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah GL Book</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-3"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="col-md-5"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-4"><label class="form-label">Type</label><select name="book_type" class="form-select"><option value="primary">Primary</option><option value="local">Local</option><option value="tax">Tax</option><option value="management">Management</option></select></div>
<div class="col-md-4"><label class="form-label">Currency</label><select name="currency_id" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-8"><label class="form-label">Retained Earnings Account</label><select name="retained_earnings_account_id" class="form-select"><option value="">-</option><?php foreach ($postable as $account) : ?><option value="<?= (int) $account['id'] ?>"><?= esc($account['account_code'] . ' - ' . $account['account_name']) ?></option><?php endforeach; ?></select></div>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="addGlColumn"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/gl-columns') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah GL Column</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-4"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="col-md-8"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Type</label><select name="column_type" class="form-select"><option value="actual">Actual</option><option value="budget">Budget</option><option value="variance">Variance</option></select></div><div class="col-md-6"><label class="form-label">Sequence</label><input name="sequence_no" type="number" min="1" value="10" class="form-control" required></div>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="addCostType"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/cost-types') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Cost Type</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-4"><label class="form-label">Code</label><input name="code" class="form-control" required></div><div class="col-md-8"><label class="form-label">Name</label><input name="name" class="form-control" required></div><div class="col-md-12"><label class="form-label">Valuation Method</label><select name="valuation_method" class="form-select"><option value="standard">Standard</option><option value="moving_average">Moving Average</option><option value="fifo">FIFO</option></select></div>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="addItemCost"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/master/item-costs') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Item Cost</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-4"><label class="form-label">Item</label><select name="product_id" class="form-select" required><?php foreach ($products as $product) : ?><option value="<?= (int) $product['id'] ?>"><?= esc($product['code'] . ' - ' . $product['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Cost Type</label><select name="cost_type_id" class="form-select" required><?php foreach ($costTypes as $type) : ?><option value="<?= (int) $type['id'] ?>"><?= esc($type['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Currency</label><select name="currency_id" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Unit Cost</label><input name="unit_cost" type="number" step="0.0001" min="0" class="form-control" required></div><div class="col-md-4"><label class="form-label">Effective From</label><input name="effective_from" type="date" value="<?= date('Y-m-d') ?>" class="form-control" required></div>
</div><div class="modal-footer"><button class="btn btn-primary" <?= $products === [] || $costTypes === [] ? 'disabled' : '' ?>>Simpan</button></div></form></div></div>
<div class="modal fade" id="addFiscalPeriod"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/fiscal-periods') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Fiscal Period</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-6"><label class="form-label">Year</label><input name="year" type="number" min="2000" max="2100" value="<?= date('Y') ?>" class="form-control" required></div><div class="col-md-6"><label class="form-label">Period</label><input name="period" type="number" min="1" max="13" value="<?= date('n') ?>" class="form-control" required></div><div class="col-md-6"><label class="form-label">Starts On</label><input name="starts_on" type="date" class="form-control" required></div><div class="col-md-6"><label class="form-label">Ends On</label><input name="ends_on" type="date" class="form-control" required></div>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="closeModulePeriod"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/module-periods/close') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Close Module Period</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-7"><label class="form-label">Fiscal Period</label><select name="fiscal_period_id" class="form-select" required><?php foreach ($fiscalPeriods as $period) : ?><option value="<?= (int) $period['id'] ?>"><?= esc($period['year'] . '/' . str_pad((string) $period['period'], 2, '0', STR_PAD_LEFT)) ?></option><?php endforeach; ?></select></div><div class="col-md-5"><label class="form-label">Module</label><select name="module_code" class="form-select" required><?php foreach ($moduleCodes as $moduleCode) : ?><option value="<?= esc($moduleCode) ?>"><?= esc(strtoupper($moduleCode)) ?></option><?php endforeach; ?></select></div>
</div><div class="modal-footer"><button class="btn btn-primary" <?= $fiscalPeriods === [] ? 'disabled' : '' ?>>Close Module</button></div></form></div></div>
<div class="modal fade" id="addJournal"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/master/journals') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Manual Journal</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-md-4"><label class="form-label">GL Book</label><select name="gl_book_id" class="form-select" required><?php foreach ($glBooks as $book) : ?><?php if ($book['status'] === 'active') : ?><option value="<?= (int) $book['id'] ?>"><?= esc($book['code']) ?></option><?php endif; ?><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Journal Date</label><input name="journal_date" type="date" value="<?= date('Y-m-d') ?>" class="form-control" required></div><div class="col-md-4"><label class="form-label">Description</label><input name="description" class="form-control" required></div>
<div class="col-md-5"><label class="form-label">Debit Account</label><select name="debit_account_id" class="form-select" required><?php foreach ($postable as $account) : ?><option value="<?= (int) $account['id'] ?>"><?= esc($account['account_code'] . ' - ' . $account['account_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Debit</label><input name="debit_amount" type="number" step="0.0001" min="0.0001" class="form-control" required></div><div class="col-md-4"><label class="form-label">Line Desc</label><input name="debit_description" class="form-control"></div>
<div class="col-md-5"><label class="form-label">Credit Account</label><select name="credit_account_id" class="form-select" required><?php foreach ($postable as $account) : ?><option value="<?= (int) $account['id'] ?>"><?= esc($account['account_code'] . ' - ' . $account['account_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Credit</label><input name="credit_amount" type="number" step="0.0001" min="0.0001" class="form-control" required></div><div class="col-md-4"><label class="form-label">Line Desc</label><input name="credit_description" class="form-control"></div>
</div><div class="modal-footer"><button class="btn btn-primary" <?= $glBooks === [] || $postable === [] ? 'disabled' : '' ?>>Simpan Draft</button></div></form></div></div>
<?php endif; ?>
<?= $this->endSection() ?>

<?php if ($canManage) : ?><?= $this->section('scripts') ?>
<script>
document.querySelectorAll('.js-edit-account').forEach(function (button) { button.addEventListener('click', function () { var form = document.querySelector('.js-account-form'); form.action = form.dataset.action + '/' + button.dataset.id; form.querySelector('[data-field="name"]').value = button.dataset.name; form.querySelector('[data-field="parent"]').value = button.dataset.parent === '0' ? '' : button.dataset.parent; form.querySelector('[data-field="type"]').value = button.dataset.type; form.querySelector('[data-field="normal"]').value = button.dataset.normal; form.querySelector('[data-field="postable"]').checked = button.dataset.postable === '1'; }); });
document.querySelectorAll('.js-edit-bank').forEach(function (button) { button.addEventListener('click', function () { var form = document.querySelector('.js-bank-form'); form.action = form.dataset.action + '/' + button.dataset.id; ['name', 'type', 'account', 'currency', 'bank', 'number'].forEach(function (key) { form.querySelector('[data-field="' + key + '"]').value = button.dataset[key]; }); form.querySelector('[data-field="branch"]').value = button.dataset.branch === '0' ? '' : button.dataset.branch; }); });
document.querySelectorAll('.js-edit-rate').forEach(function (button) { button.addEventListener('click', function () { var form = document.querySelector('.js-rate-form'); form.action = form.dataset.action + '/' + button.dataset.id; ['currency', 'date', 'type', 'rate'].forEach(function (key) { form.querySelector('[data-field="' + key + '"]').value = button.dataset[key]; }); }); });
</script>
<?= $this->endSection() ?><?php endif; ?>
