<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>Finance Master<?= $this->endSection() ?>

<?= $this->section('content') ?>
<?php $nextStatus = static fn (string $status): string => $status === 'active' ? 'inactive' : 'active'; ?>
<div class="page-title-box d-flex align-items-center justify-content-between">
    <div>
        <h4 class="mb-sm-0 font-size-18">Finance Master</h4>
        <p class="text-muted mb-0"><?= esc($tenantContext['company_name']) ?> / COA, kas-bank, dan kurs</p>
    </div>
    <?php if ($canManage) : ?>
        <div class="dropdown"><button class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">Tambah Data</button><div class="dropdown-menu">
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addAccount">Chart of Account</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addCashBank">Cash/Bank Account</button>
            <button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addRate">Exchange Rate</button>
        </div></div>
    <?php else : ?><span class="badge bg-info">Read only</span><?php endif; ?>
</div>
<?php if (session('message') !== null) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors') !== null) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>

<ul class="nav nav-tabs mb-3" role="tablist">
    <li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#coa">Chart of Accounts</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#cash-bank">Cash &amp; Bank</button></li>
    <li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#rates">Exchange Rate</button></li>
</ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="coa"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>Code</th><th>Account Name</th><th>Type</th><th>Parent</th><th>Normal</th><th>Posting</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($accounts as $account) : ?><tr>
        <td><strong><?= esc($account['account_code']) ?></strong></td><td><?= esc($account['account_name']) ?></td><td><?= esc($account['account_type']) ?></td><td><?= esc($account['parent_code'] ?? '-') ?></td><td><?= esc($account['normal_balance']) ?></td><td><?= (bool) $account['is_postable'] ? 'Ya' : 'Tidak' ?></td><td><?= esc($account['status']) ?></td>
        <?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-account" data-bs-toggle="modal" data-bs-target="#editAccount" data-id="<?= (int) $account['id'] ?>" data-name="<?= esc($account['account_name'], 'attr') ?>" data-parent="<?= (int) ($account['parent_id'] ?? 0) ?>" data-type="<?= esc($account['account_type'], 'attr') ?>" data-normal="<?= esc($account['normal_balance'], 'attr') ?>" data-postable="<?= (int) $account['is_postable'] ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url('finance/master/status/account/' . $account['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($account['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $account['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?>
    </tr><?php endforeach; ?><?php if ($accounts === []) : ?><tr><td colspan="<?= $canManage ? '8' : '7' ?>" class="text-center text-muted py-4">Belum ada akun.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
<div class="tab-pane fade" id="cash-bank"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>Code / Name</th><th>Type</th><th>Site</th><th>COA</th><th>Currency</th><th>Bank / Rekening</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($cashBanks as $cashBank) : ?><tr>
        <td><strong><?= esc($cashBank['code']) ?></strong><br><small><?= esc($cashBank['name']) ?></small></td><td><?= esc($cashBank['account_type']) ?></td><td><?= esc($cashBank['branch_code'] ?? 'All') ?></td><td><?= esc($cashBank['account_code']) ?></td><td><?= esc($cashBank['currency_code']) ?></td><td><?= esc(trim(($cashBank['bank_name'] ?? '') . ' ' . ($cashBank['account_number_masked'] ?? '')) ?: '-') ?></td><td><?= esc($cashBank['status']) ?></td>
        <?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-bank" data-bs-toggle="modal" data-bs-target="#editCashBank" data-id="<?= (int) $cashBank['id'] ?>" data-name="<?= esc($cashBank['name'], 'attr') ?>" data-type="<?= esc($cashBank['account_type'], 'attr') ?>" data-branch="<?= (int) ($cashBank['branch_id'] ?? 0) ?>" data-account="<?= (int) $cashBank['account_id'] ?>" data-currency="<?= (int) $cashBank['currency_id'] ?>" data-bank="<?= esc($cashBank['bank_name'] ?? '', 'attr') ?>" data-number="<?= esc($cashBank['account_number_masked'] ?? '', 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url('finance/master/status/cash-bank/' . $cashBank['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($cashBank['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $cashBank['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?>
    </tr><?php endforeach; ?><?php if ($cashBanks === []) : ?><tr><td colspan="<?= $canManage ? '8' : '7' ?>" class="text-center text-muted py-4">Belum ada kas/bank.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
<div class="tab-pane fade" id="rates"><div class="card"><div class="card-body"><div class="table-responsive"><table class="table table-hover align-middle mb-0">
    <thead><tr><th>Date</th><th>Currency</th><th>Type</th><th>Rate to Base</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead>
    <tbody><?php foreach ($rates as $rate) : ?><tr>
        <td><?= esc($rate['rate_date']) ?></td><td><?= esc($rate['currency_code']) ?></td><td><?= esc($rate['rate_type']) ?></td><td><?= esc($rate['rate_to_base']) ?></td><td><?= esc($rate['status']) ?></td>
        <?php if ($canManage) : ?><td class="text-end text-nowrap"><button class="btn btn-outline-primary btn-sm js-edit-rate" data-bs-toggle="modal" data-bs-target="#editRate" data-id="<?= (int) $rate['id'] ?>" data-currency="<?= (int) $rate['currency_id'] ?>" data-date="<?= esc($rate['rate_date'], 'attr') ?>" data-type="<?= esc($rate['rate_type'], 'attr') ?>" data-rate="<?= esc($rate['rate_to_base'], 'attr') ?>">Edit</button> <form class="d-inline" method="post" action="<?= site_url('finance/master/status/exchange-rate/' . $rate['id']) ?>"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $nextStatus($rate['status']) ?>"><button class="btn btn-outline-danger btn-sm"><?= $rate['status'] === 'active' ? 'Hapus' : 'Aktifkan' ?></button></form></td><?php endif; ?>
    </tr><?php endforeach; ?><?php if ($rates === []) : ?><tr><td colspan="<?= $canManage ? '6' : '5' ?>" class="text-center text-muted py-4">Belum ada kurs.</td></tr><?php endif; ?></tbody>
</table></div></div></div></div>
</div>

<?php if ($canManage) : ?>
<div class="modal fade" id="addAccount"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Chart of Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-4"><label class="form-label">Code</label><input name="account_code" class="form-control" required></div><div class="col-8"><label class="form-label">Account Name</label><input name="account_name" class="form-control" required></div><?php include __DIR__ . '/partials/account_fields.php'; ?>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editAccount"><div class="modal-dialog"><form class="modal-content js-account-form" method="post" data-action="<?= site_url('finance/master/accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Chart of Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2">
<div class="col-12"><label class="form-label">Account Name</label><input name="account_name" data-field="name" class="form-control" required></div><?php include __DIR__ . '/partials/account_fields.php'; ?>
</div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<?php $bankFields = static function () use ($branches, $postable, $currencies): void { ?>
<div class="col-md-6"><label class="form-label">Name</label><input name="name" data-field="name" class="form-control" required></div><div class="col-md-3"><label class="form-label">Type</label><select name="account_type" data-field="type" class="form-select"><option value="cash">Cash</option><option value="bank">Bank</option></select></div><div class="col-md-3"><label class="form-label">Site</label><select name="branch_id" data-field="branch" class="form-select"><option value="">All</option><?php foreach ($branches as $branch) : ?><option value="<?= (int) $branch['id'] ?>"><?= esc($branch['code']) ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label">COA Posting</label><select name="account_id" data-field="account" class="form-select" required><?php foreach ($postable as $account) : ?><option value="<?= (int) $account['id'] ?>"><?= esc($account['account_code'] . ' - ' . $account['account_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Currency</label><select name="currency_id" data-field="currency" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="form-label">Bank Name</label><input name="bank_name" data-field="bank" class="form-control"></div><div class="col-md-6"><label class="form-label">Masked Account No.</label><input name="account_number_masked" data-field="number" class="form-control" placeholder="****1234"></div>
<?php }; ?>
<div class="modal fade" id="addCashBank"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/master/cash-bank-accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Cash/Bank Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-3"><label class="form-label">Code</label><input name="code" class="form-control" required></div><?php $bankFields(); ?></div><div class="modal-footer"><button class="btn btn-primary" <?= $postable === [] ? 'disabled' : '' ?>>Simpan</button></div></form></div></div>
<div class="modal fade" id="editCashBank"><div class="modal-dialog modal-lg"><form class="modal-content js-bank-form" method="post" data-action="<?= site_url('finance/master/cash-bank-accounts') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Cash/Bank Account</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><?php $bankFields(); ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<?php $rateFields = static function () use ($currencies): void { ?><div class="col-md-4"><label class="form-label">Currency</label><select name="currency_id" data-field="currency" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Date</label><input type="date" name="rate_date" data-field="date" class="form-control" required></div><div class="col-md-4"><label class="form-label">Type</label><select name="rate_type" data-field="type" class="form-select"><option value="middle">Middle</option><option value="buy">Buy</option><option value="sell">Sell</option></select></div><div class="col-md-6"><label class="form-label">Rate to Base</label><input name="rate_to_base" data-field="rate" class="form-control" required></div><?php }; ?>
<div class="modal fade" id="addRate"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/master/exchange-rates') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Exchange Rate</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><?php $rateFields(); ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan</button></div></form></div></div>
<div class="modal fade" id="editRate"><div class="modal-dialog"><form class="modal-content js-rate-form" method="post" data-action="<?= site_url('finance/master/exchange-rates') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Edit Exchange Rate</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><?php $rateFields(); ?></div><div class="modal-footer"><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>
<?php endif; ?>
<?= $this->endSection() ?>

<?php if ($canManage) : ?><?= $this->section('scripts') ?>
<script>
document.querySelectorAll('.js-edit-account').forEach(function (button) { button.addEventListener('click', function () { var form = document.querySelector('.js-account-form'); form.action = form.dataset.action + '/' + button.dataset.id; form.querySelector('[data-field="name"]').value = button.dataset.name; form.querySelector('[data-field="parent"]').value = button.dataset.parent === '0' ? '' : button.dataset.parent; form.querySelector('[data-field="type"]').value = button.dataset.type; form.querySelector('[data-field="normal"]').value = button.dataset.normal; form.querySelector('[data-field="postable"]').checked = button.dataset.postable === '1'; }); });
document.querySelectorAll('.js-edit-bank').forEach(function (button) { button.addEventListener('click', function () { var form = document.querySelector('.js-bank-form'); form.action = form.dataset.action + '/' + button.dataset.id; ['name', 'type', 'account', 'currency', 'bank', 'number'].forEach(function (key) { form.querySelector('[data-field="' + key + '"]').value = button.dataset[key]; }); form.querySelector('[data-field="branch"]').value = button.dataset.branch === '0' ? '' : button.dataset.branch; }); });
document.querySelectorAll('.js-edit-rate').forEach(function (button) { button.addEventListener('click', function () { var form = document.querySelector('.js-rate-form'); form.action = form.dataset.action + '/' + button.dataset.id; ['currency', 'date', 'type', 'rate'].forEach(function (key) { form.querySelector('[data-field="' + key + '"]').value = button.dataset[key]; }); }); });
</script>
<?= $this->endSection() ?><?php endif; ?>
