<?= $this->extend('layouts/dashboard') ?>

<?= $this->section('title') ?>Finance Transactions<?= $this->endSection() ?>

<?= $this->section('content') ?>
<?php
$purchaseOrders = $purchaseOrders ?? [];
$salesOrders = $salesOrders ?? [];
$statusBadge = static function (string $status): string {
    return match ($status) {
        'paid' => 'success',
        'partial_paid' => 'warning',
        'unpaid' => 'danger',
        'draft' => 'secondary',
        default => 'info',
    };
};
$money = static fn (mixed $value): string => number_format((float) $value, 2, ',', '.');
?>
<div class="page-title-box d-flex align-items-center justify-content-between">
    <div><h4 class="mb-sm-0 font-size-18">Finance Transactions</h4><p class="text-muted mb-0"><?= esc($tenantContext['company_name']) ?> / AP, AR, Payment</p></div>
    <?php if ($canManage) : ?><div class="dropdown"><button class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">Tambah Transaksi</button><div class="dropdown-menu"><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addPurchaseInvoice">Purchase Invoice</button><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addSalesInvoice">Sales Invoice</button><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addPayment">Payment</button></div></div><?php else : ?><span class="badge bg-info">Read only</span><?php endif; ?>
</div>
<?php if (session('message') !== null) : ?><div class="alert alert-success"><?= esc(session('message')) ?></div><?php endif; ?>
<?php if (session('errors') !== null) : ?><div class="alert alert-danger"><?php foreach ((array) session('errors') as $error) : ?><div><?= esc($error) ?></div><?php endforeach; ?></div><?php endif; ?>

<div class="row">
    <div class="col-md-4"><div class="card border-secondary"><div class="card-body"><h5 class="card-title">Purchase Invoices</h5><p class="display-6 mb-0"><?= count($purchaseInvoices) ?></p></div></div></div>
    <div class="col-md-4"><div class="card border-secondary"><div class="card-body"><h5 class="card-title">Sales Invoices</h5><p class="display-6 mb-0"><?= count($salesInvoices) ?></p></div></div></div>
    <div class="col-md-4"><div class="card border-secondary"><div class="card-body"><h5 class="card-title">Payments</h5><p class="display-6 mb-0"><?= count($payments) ?></p></div></div></div>
</div>

<div class="row mt-4">
    <div class="col-xl-12"><div class="card"><div class="card-body"><h4 class="card-title mb-3">Latest Purchase Invoices</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>No</th><th>Supplier</th><th>Date</th><th>Due</th><th>Total</th><th>Paid</th><th>Outstanding</th><th>Doc</th><th>Payment</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody><?php foreach ($purchaseInvoices as $invoice) : ?><tr><td><strong><?= esc($invoice['invoice_no']) ?></strong></td><td><?= esc(($invoice['supplier_code'] ?? '-') . ' - ' . ($invoice['supplier_name'] ?? '-')) ?></td><td><?= esc($invoice['invoice_date']) ?></td><td><?= esc($invoice['due_date']) ?></td><td><?= esc($money($invoice['total_amount'])) ?></td><td><?= esc($money($invoice['paid_amount'] ?? 0)) ?></td><td><?= esc($money($invoice['outstanding_amount'] ?? $invoice['total_amount'])) ?></td><td><span class="badge bg-info"><?= esc($invoice['status']) ?></span></td><td><span class="badge bg-<?= esc($statusBadge((string) ($invoice['payment_status'] ?? 'draft'))) ?>"><?= esc($invoice['payment_status'] ?? 'draft') ?></span></td><?php if ($canManage) : ?><td class="text-end"><?php if ($invoice['status'] === 'draft') : ?><form method="post" action="<?= site_url('finance/invoices/purchase-invoices/' . $invoice['id'] . '/post') ?>"><?= csrf_field() ?><button class="btn btn-sm btn-primary">Post</button></form><?php else : ?>-<?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if ($purchaseInvoices === []) : ?><tr><td colspan="10" class="text-center text-muted py-4">Belum ada purchase invoice.</td></tr><?php endif; ?></tbody></table></div></div></div></div>
</div>

<div class="row mt-4">
    <div class="col-xl-12"><div class="card"><div class="card-body"><h4 class="card-title mb-3">Latest Sales Invoices</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>No</th><th>Customer</th><th>Date</th><th>Due</th><th>Total</th><th>Paid</th><th>Outstanding</th><th>Doc</th><th>Payment</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody><?php foreach ($salesInvoices as $invoice) : ?><tr><td><strong><?= esc($invoice['invoice_no']) ?></strong></td><td><?= esc(($invoice['customer_code'] ?? '-') . ' - ' . ($invoice['customer_name'] ?? '-')) ?></td><td><?= esc($invoice['invoice_date']) ?></td><td><?= esc($invoice['due_date']) ?></td><td><?= esc($money($invoice['total_amount'])) ?></td><td><?= esc($money($invoice['paid_amount'] ?? 0)) ?></td><td><?= esc($money($invoice['outstanding_amount'] ?? $invoice['total_amount'])) ?></td><td><span class="badge bg-info"><?= esc($invoice['status']) ?></span></td><td><span class="badge bg-<?= esc($statusBadge((string) ($invoice['payment_status'] ?? 'draft'))) ?>"><?= esc($invoice['payment_status'] ?? 'draft') ?></span></td><?php if ($canManage) : ?><td class="text-end"><?php if ($invoice['status'] === 'draft') : ?><form method="post" action="<?= site_url('finance/invoices/sales-invoices/' . $invoice['id'] . '/post') ?>"><?= csrf_field() ?><button class="btn btn-sm btn-primary">Post</button></form><?php else : ?>-<?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if ($salesInvoices === []) : ?><tr><td colspan="10" class="text-center text-muted py-4">Belum ada sales invoice.</td></tr><?php endif; ?></tbody></table></div></div></div></div>
</div>

<div class="card mt-4"><div class="card-body"><h4 class="card-title mb-3">Latest Payments</h4><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>No</th><th>Type</th><th>Partner</th><th>Date</th><th>Amount</th><th>Status</th><?php if ($canManage) : ?><th class="text-end">Aksi</th><?php endif; ?></tr></thead><tbody><?php foreach ($payments as $payment) : ?><tr><td><strong><?= esc($payment['payment_no']) ?></strong></td><td><?= esc($payment['payment_type']) ?></td><td><?= esc(($payment['supplier_code'] !== null ? $payment['supplier_code'] . ' - ' . $payment['supplier_name'] : ($payment['customer_code'] !== null ? $payment['customer_code'] . ' - ' . $payment['customer_name'] : '-'))) ?></td><td><?= esc($payment['payment_date']) ?></td><td><?= esc($money($payment['amount'])) ?></td><td><?= esc($payment['status']) ?></td><?php if ($canManage) : ?><td class="text-end"><?php if ($payment['status'] === 'draft') : ?><form method="post" action="<?= site_url('finance/invoices/payments/' . $payment['id'] . '/post') ?>"><?= csrf_field() ?><button class="btn btn-sm btn-primary">Post</button></form><?php else : ?><button class="btn btn-sm btn-secondary js-open-allocations" data-payment-id="<?= (int) $payment['id'] ?>">Allocations</button><?php endif; ?></td><?php endif; ?></tr><?php endforeach; ?><?php if ($payments === []) : ?><tr><td colspan="7" class="text-center text-muted py-4">Belum ada pembayaran.</td></tr><?php endif; ?></tbody></table></div></div></div>

<?php if ($canManage) : ?>
<div class="modal fade" id="addPurchaseInvoice"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/invoices/purchase-invoices') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Purchase Invoice</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-12"><label class="form-label">Sumber Purchase Order</label><select name="purchase_order_id" id="purchaseOrderSource" class="form-select"><option value="">Manual / tanpa PO</option><?php foreach ($purchaseOrders as $po) : ?><option value="<?= (int) $po['id'] ?>" data-partner="<?= (int) $po['supplier_id'] ?>" data-currency="<?= (int) $po['currency_id'] ?>" data-total="<?= esc((string) $po['total_amount']) ?>"><?= esc($po['po_no'] . ' - ' . ($po['supplier_name'] ?? '-') . ' - ' . $po['status']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Supplier</label><select name="supplier_id" id="purchaseInvoicePartner" class="form-select" required><?php foreach ($suppliers as $supplier) : ?><option value="<?= (int) $supplier['id'] ?>"><?= esc($supplier['code'] . ' - ' . $supplier['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Invoice No</label><input name="invoice_no" class="form-control" required></div><div class="col-md-6"><label class="form-label">Invoice Date</label><input type="date" name="invoice_date" class="form-control" required value="<?= date('Y-m-d') ?>"></div><div class="col-md-6"><label class="form-label">Due Date</label><input type="date" name="due_date" class="form-control" required value="<?= date('Y-m-d') ?>"></div><div class="col-md-6"><label class="form-label">Currency</label><select name="currency_id" id="purchaseInvoiceCurrency" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Subtotal</label><input name="subtotal" id="purchaseInvoiceSubtotal" type="number" step="0.0001" min="0" class="form-control" required></div><div class="col-md-6"><label class="form-label">Tax Amount</label><input name="tax_amount" id="purchaseInvoiceTax" type="number" step="0.0001" min="0" class="form-control" required value="0.0000"></div><div class="col-md-6"><label class="form-label">Total Amount</label><input name="total_amount" id="purchaseInvoiceTotal" type="number" step="0.0001" min="0" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Draft</button></div></form></div></div>
<div class="modal fade" id="addSalesInvoice"><div class="modal-dialog modal-lg"><form class="modal-content" method="post" action="<?= site_url('finance/invoices/sales-invoices') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Sales Invoice</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-12"><label class="form-label">Sumber Sales Order</label><select name="sales_order_id" id="salesOrderSource" class="form-select"><option value="">Manual / tanpa SO</option><?php foreach ($salesOrders as $so) : ?><option value="<?= (int) $so['id'] ?>" data-partner="<?= (int) $so['customer_id'] ?>" data-currency="<?= (int) $so['currency_id'] ?>" data-total="<?= esc((string) $so['total_amount']) ?>"><?= esc($so['order_no'] . ' - ' . ($so['customer_name'] ?? '-') . ' - ' . $so['status']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Customer</label><select name="customer_id" id="salesInvoicePartner" class="form-select" required><?php foreach ($customers as $customer) : ?><option value="<?= (int) $customer['id'] ?>"><?= esc($customer['code'] . ' - ' . $customer['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Invoice No</label><input name="invoice_no" class="form-control" required></div><div class="col-md-6"><label class="form-label">Invoice Date</label><input type="date" name="invoice_date" class="form-control" required value="<?= date('Y-m-d') ?>"></div><div class="col-md-6"><label class="form-label">Due Date</label><input type="date" name="due_date" class="form-control" required value="<?= date('Y-m-d') ?>"></div><div class="col-md-6"><label class="form-label">Currency</label><select name="currency_id" id="salesInvoiceCurrency" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Subtotal</label><input name="subtotal" id="salesInvoiceSubtotal" type="number" step="0.0001" min="0" class="form-control" required></div><div class="col-md-6"><label class="form-label">Tax Amount</label><input name="tax_amount" id="salesInvoiceTax" type="number" step="0.0001" min="0" class="form-control" required value="0.0000"></div><div class="col-md-6"><label class="form-label">Total Amount</label><input name="total_amount" id="salesInvoiceTotal" type="number" step="0.0001" min="0" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Draft</button></div></form></div></div>
<div class="modal fade" id="addPayment"><div class="modal-dialog"><form class="modal-content" method="post" action="<?= site_url('finance/invoices/payments') ?>"><?= csrf_field() ?><div class="modal-header"><h5 class="modal-title">Tambah Payment</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body row g-2"><div class="col-md-6"><label class="form-label">Payment Type</label><select id="paymentType" name="payment_type" class="form-select" required><option value="outgoing">Outgoing</option><option value="incoming">Incoming</option></select></div><div class="col-md-6"><label class="form-label">Payment No</label><input name="payment_no" class="form-control" required></div><div class="col-md-6 js-payment-supplier"><label class="form-label">Supplier</label><select name="supplier_id" class="form-select"><?php foreach ($suppliers as $supplier) : ?><option value="<?= (int) $supplier['id'] ?>"><?= esc($supplier['code'] . ' - ' . $supplier['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 js-payment-customer d-none"><label class="form-label">Customer</label><select name="customer_id" class="form-select"><?php foreach ($customers as $customer) : ?><option value="<?= (int) $customer['id'] ?>"><?= esc($customer['code'] . ' - ' . $customer['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Payment Date</label><input type="date" name="payment_date" class="form-control" required value="<?= date('Y-m-d') ?>"></div><div class="col-md-6"><label class="form-label">Currency</label><select name="currency_id" class="form-select" required><?php foreach ($currencies as $currency) : ?><option value="<?= (int) $currency['id'] ?>"><?= esc($currency['code']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Bank Account</label><select name="bank_account_id" class="form-select"><option value="">-</option><?php foreach ($cashBanks as $bank) : ?><option value="<?= (int) $bank['id'] ?>"><?= esc($bank['code'] . ' - ' . $bank['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Amount</label><input name="amount" type="number" step="0.0001" min="0" class="form-control" required></div></div><div class="modal-footer"><button class="btn btn-primary">Simpan Draft</button></div></form></div></div>
<?php endif; ?>
<?= $this->endSection() ?>

<?= $this->section('scripts') ?>
<script>
(function(){function set(id,v){var e=document.getElementById(id);if(e&&v!==undefined&&v!==null&&v!=='')e.value=String(v)}function money(id,v){var e=document.getElementById(id);if(e)e.value=Number(v||0).toFixed(4)}function bind(source,partner,currency,subtotal,tax,total){var s=document.getElementById(source);if(!s)return;s.addEventListener('change',function(){var o=s.selectedOptions[0];if(!o||!o.value)return;set(partner,o.dataset.partner);set(currency,o.dataset.currency);money(subtotal,o.dataset.total);money(tax,0);money(total,o.dataset.total)})}bind('purchaseOrderSource','purchaseInvoicePartner','purchaseInvoiceCurrency','purchaseInvoiceSubtotal','purchaseInvoiceTax','purchaseInvoiceTotal');bind('salesOrderSource','salesInvoicePartner','salesInvoiceCurrency','salesInvoiceSubtotal','salesInvoiceTax','salesInvoiceTotal');})();
</script>
<script>
(function(){var t=document.getElementById('paymentType'),s=document.querySelector('.js-payment-supplier'),c=document.querySelector('.js-payment-customer');if(!t||!s||!c)return;function u(){if(t.value==='incoming'){s.classList.add('d-none');c.classList.remove('d-none')}else{s.classList.remove('d-none');c.classList.add('d-none')}}t.addEventListener('change',u);u();})();
</script>
<?= $this->endSection() ?>
